Prepare docker ci/cd (#16)
* Prepare docker ci/cd

Merge changes with develop

* Fix issues with github actions

* Fix naming issue with github actions

* Update github actions, delete change docker action

* Update ci/cd

* Solve PR issues with dockerignore files

* Fix code issues, remove unused variables

* Resolve again linting issues

* delete comments from dockerfile

* changed frontend dockerfile to run vite and adapted docker compose for CI/CD

---------

Co-authored-by: FrancoMarengo <tenamarengo.11@gmail.com>

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,19 +1,49 @@
-FROM node:18-alpine AS build
+FROM node:18-alpine AS base
 
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
-COPY package*.json ./
-RUN npm install
 
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN npm run build
 
-FROM node:18-alpine
+COPY vite.config.js ./
+COPY eslint.config.js ./
 
+# Build the Vite app
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM base AS runner
 WORKDIR /app
-COPY --from=build /app/.next ./.next
-COPY --from=build /app/node_modules ./node_modules
-COPY --from=build /app/package.json ./package.json
+
+ENV NODE_ENV=production
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 viteuser
+
+COPY --from=builder --chown=viteuser:nodejs /app/dist ./dist
+
+RUN npm install -g serve
+
+USER viteuser
 
 EXPOSE 3000
 
-CMD ["npm", "start"]
+ENV PORT=3000
+
+CMD ["serve", "-s", "dist", "-l", "3000"]
